<a href="https://colab.research.google.com/github/Leeonejae6708/python_itwill/blob/main/Python18_itwill.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 필요한 모듈 lmport

In [4]:
  import pandas as pd # pandas 패키지를 pd라는 별칭으로 사용

## Serise

* 한가지 타입의 값 여러 개를 저장할 수 있는 1차원 모양의 데이터 타입(클래스)
* 축(axis) 레이블을 가지고 있는 1차원 배열

In [5]:
s = pd.Series([1, 3, -5, -7])    # pd.Series 생성자 호출 -> Series 객체 생성

In [8]:
type(s)

pandas.core.series.Series

In [12]:
print(type(s))

<class 'pandas.core.series.Series'>

In [11]:
s

0    1
1    3
2   -5
3   -7
dtype: int64

In [15]:
print(s)

0    1
1    3
2   -5
3   -7
dtype: int64

In [16]:
s.index    # Series의 index 속성

RangeIndex(start=0, stop=4, step=1)

In [17]:
s.values   # Series의 values 속성

array([ 1,  3, -5, -7])

Series 객체를 생성할 때 index 파라미터를 설정하지 않으면 0부터 1씩 증가하는 정수들로 이루어진 인덱스가 자동으로 부여

## indexing, slicing

`iloc` vs `loc`
* `iloc`: 정수 인덱스 기반으로 원소를 참조. list의 인덱스를 사용하는 방법과 동일  ->> 사물함 몇 번째!
* `loc`: 축 레이블 기반으로 원소를 참조  ->> 사물함 이름표!

In [25]:
s.iloc[0]    # Series의 첫 번째 원소 참조(선택)

np.int64(1)

In [26]:
s.iloc[-1]   # Series의 마지막 원소 선택

np.int64(-7)

In [29]:
s.iloc[:2]   # slicing의 시작 인덱스 0은 생략 가능. 첫 번째 원소부터 두 번째 원소까지 slicing

0    1
1    3
dtype: int64

In [30]:
s.iloc[-2:]  # 마지막 2개 원소를 slicing. 음수 인덱스 사용 가능. 마지막 인덱스는 생략 가능

2   -5
3   -7
dtype: int64

In [33]:
s.loc[0]  # Series에서 레이블이 0인 원소를 참조

np.int64(1)

In [35]:
s.loc[3]  # Series에서 레이블이 -3인 원소를 참조

np.int64(-7)

In [37]:
# s.loc[-1] -> ValueError, KeyError 발생 ->> 리스트처럼 자동으로 부여되는 음수 인덱스는 없음

In [38]:
s.loc[:2]  # loc 속성을 사용할 때도 시작 인덱스(레이블)은 생략 가능. 마지막 인덱스(레이블)의 원소도 포함!

0    1
1    3
2   -5
dtype: int64

In [46]:
s2 = pd.Series(data = [1, 3, -5, -7, 9],
               index=['a', 'b', 'x', 'y', 'c'])
s2

a    1
b    3
x   -5
y   -7
c    9
dtype: int64

In [41]:
s2.index

Index(['a', 'b', 'x', 'y', 'c'], dtype='object')

In [42]:
s2.values

array([ 1,  3, -5, -7,  9])

In [45]:
s2.iloc[0]

np.int64(1)

In [47]:
s2.iloc[-1]

np.int64(9)

In [48]:
s2.loc['a']

np.int64(1)

In [49]:
s2.loc['c']

np.int64(9)

In [54]:
s2.iloc[:2]

a    1
b    3
dtype: int64

In [53]:
s2.loc[:'b']

a    1
b    3
dtype: int64

## fancy indexing

In [56]:
s2[['a', 'b', 'c']]   # s2.loc[['a', 'b', 'c']]와 동일

a    1
b    3
c    9
dtype: int64

In [59]:
s2.iloc[[0, 1, 4]]

a    1
b    3
c    9
dtype: int64

## boolean indexing

In [60]:
s2[[False, False, True, True, False]]   # True -> 선택하겠다! / False -> 선택하지 않겠다!
# ->> True인 것들만 출력

x   -5
y   -7
dtype: int64

Series 객체에서 산술 연산과 논리 연산은 각각의 원소들에 대해서 반복해서 연산을 수행

In [62]:
s2 + 1

a     2
b     4
x    -4
y    -6
c    10
dtype: int64

In [64]:
s2 > 0  # 각각의 원소들에 대해서 2보다 큰 지를 비교한 결과값을 boolean형(True/False)으로 저장한 Series

a     True
b     True
x    False
y    False
c     True
dtype: bool

In [67]:
s2[s2>0]  # Series s2의 원소들 중에서 양수들만 선택한 Series

a    1
b    3
c    9
dtype: int64

In [68]:
s2[s2<0]  # Series s2의 원소들 중에서 음수들만 선택한 Series

x   -5
y   -7
dtype: int64

## Dataframe

table 모양(행(row)과 열(column을 가지고 있는)의 2차원 데이터 타입

In [70]:
data = {
    'city': ['서울'] * 3 + ['경기'] * 3,
    'year': [2022, 2023, 2024] * 2,
    'pop' : [0.8, 0.9, 9.5,1.0, 1.2, 1.1]
}
data

{'city': ['서울', '서울', '서울', '경기', '경기', '경기'],
 'year': [2022, 2023, 2024, 2022, 2023, 2024],
 'pop': [0.8, 0.9, 9.5, 1.0, 1.2, 1.1]}

In [73]:
df = pd.DataFrame(data)
type(df)

pandas.core.frame.DataFrame

In [76]:
df

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5
3   경기  2022  1.0
4   경기  2023  1.2
5   경기  2024  1.1

## Dataframe의 속성(attributes)

In [77]:
df.index   # 행(row)의 레이블

RangeIndex(start=0, stop=6, step=1)

In [79]:
df.columns # 열(column)의 레이블

Index(['city', 'year', 'pop'], dtype='object')

In [86]:
df.columns[0]   # 첫 번째 컬럼 이름

'city'

In [ ]:
df.columns[-1]  # 마지막 컬럼 이름

In [87]:
df.shape        # (행 개수, 열 개수) tuple

(6, 3)

In [88]:
df.values

array([['서울', 2022, 0.8],
       ['서울', 2023, 0.9],
       ['서울', 2024, 9.5],
       ['경기', 2022, 1.0],
       ['경기', 2023, 1.2],
       ['경기', 2024, 1.1]], dtype=object)

## Dataframe에서 column 선택

* `df['column_name']`
* `df.column_name`
  * 컬럼 이름이 변수 이름 규칙에 맞지 않는 경우에는 사용할 수 없음
    * 변수 이름은 영문자, 숫자, 밑줄(underscore)만 사용할 수 있음
    * 변수 이름은 숫자로 시작할 수 없음
    * 파이썬의 키워드들(if, for, def, ...)은 변수 이름으로 사용할 수 없음
  * 컬럼의 이름이 Dataframe이 가지고 있는 속성(변수, 메서드) 이름과 같은 경우에는 사용할 수 없음

In [90]:
df['city']   # Dataframe df에서 city 컬럼만 선택

0    서울
1    서울
2    서울
3    경기
4    경기
5    경기
Name: city, dtype: object

In [91]:
df.city

0    서울
1    서울
2    서울
3    경기
4    경기
5    경기
Name: city, dtype: object

In [92]:
df['pop']   # Datafrmae에서 pop 컬럼 선택

0    0.8
1    0.9
2    9.5
3    1.0
4    1.2
5    1.1
Name: pop, dtype: float64

In [93]:
df.pop     # Dataframe의 메서드 이름과 같기 때문에 이 방식으론 컬럼 선택 불가.  -> Datafrmae.pop() 함수 이름(객체)

<bound method DataFrame.pop of   city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5
3   경기  2022  1.0
4   경기  2023  1.2
5   경기  2024  1.1>

In [94]:
# 여러 개의 컬럼을 함께 선택
df[['city', 'pop']]

  city  pop
0   서울  0.8
1   서울  0.9
2   서울  9.5
3   경기  1.0
4   경기  1.2
5   경기  1.1

(주의)
* `df['column_name']`: Dataframe에서 컬럼 1개 선택. 그 결과는 **Series**.
* `df[['column_name']]`: Dataframe에서 컬럼 1개를 선택한 새로운 **Dataframe**. -> 컬럼이 1개인 Dataframe

In [95]:
df['pop']   # -> Series

0    0.8
1    0.9
2    9.5
3    1.0
4    1.2
5    1.1
Name: pop, dtype: float64

In [97]:
print(type(df['pop']))

<class 'pandas.core.series.Series'>

In [96]:
df[['pop']]  # -> Dataframe        (바깥의 []는 인덱스, 안쪽의 []는 리스트)

   pop
0  0.8
1  0.9
2  9.5
3  1.0
4  1.2
5  1.1

In [98]:
print(type(df[['pop']]))

<class 'pandas.core.frame.DataFrame'>

## Dataframe에서 row 선택

* `df.iloc[정수 기반 인덱스]`
* `df.loc[행 레이블]`

In [103]:
df.iloc[0]   # Dataframe에서 첫 번째 행 선택

city      서울
year    2022
pop      0.8
Name: 0, dtype: object

In [104]:
df.iloc[-1] # Dataframe에서 마지막 행 선택

city      경기
year    2024
pop      1.1
Name: 5, dtype: object

In [105]:
df.iloc[:3]  # Dataframe에서 첫 3개의 행을 선택

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5

In [106]:
df.iloc[-3:] # Dataframe에서 마지막 3개의 행을 선택

  city  year  pop
3   경기  2022  1.0
4   경기  2023  1.2
5   경기  2024  1.1

In [111]:
df.loc[0]

city      서울
year    2022
pop      0.8
Name: 0, dtype: object

In [112]:
df.loc[:3]   # Dataframe에서 첫 번째 행부터 레이블 3인 행까지 선택(slicing)  -> 레이블 3도 포함

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5
3   경기  2022  1.0

## boolean indexin

* `df[조건식]` = `df.loc[조건식]`   -> 같은 코드
* 조건식을 만족하는 모든 행들을 선택

In [120]:
# 서울 데이터만 선택
df[df['city'] == '서울']

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5

In [121]:
# 가장 최신 자료 -> 2024년 데이터만 선택
df[df['year'] == 2024]

  city  year  pop
2   서울  2024  9.5
5   경기  2024  1.1

Series, Dataframe에서 boolean indexing을 사용할 때 주의할 점!
* `and`, `or`, `not` 키워드 사용 불가
* 대신, `&`, `|`, `~` 연산자로 사용
* 반드시 ()를 사용해서 논리 연산의 순서를 명시해야 함

In [132]:
# 2022, 2023년 데이터 선택
# df[(df['year'] == 2023) | (df['year'] == 2022)]
df[(df.year == 2023) | (df.year == 2022)]

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
3   경기  2022  1.0
4   경기  2023  1.2

In [134]:
# 도시가 서울이거나 pop의 값이 1.2 이상인 데이터 선택
df[(df['city'] == '서울') | (df['pop'] >= 1.2)]
# df[(df.city == '서울') | (df.pop >= 1.2)]  -> 이건 사용 불가.

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5
4   경기  2023  1.2

## Dataframe, Series의 메서드

In [135]:
# Dataframe.describe(): Dataframe에서 숫자형 컬럼(변수)들의 기술 통계량을 출력
# 기술 통계량: Null이 아닌 값들의 총 개수, 평균, 표준편차, 최솟값, 4분위값, 최댓값
df.describe()

              year       pop
count     6.000000  6.000000
mean   2023.000000  2.416667
std       0.894427  3.472991
min    2022.000000  0.800000
25%    2022.250000  0.925000
50%    2023.000000  1.050000
75%    2023.750000  1.175000
max    2024.000000  9.500000

In [139]:
# Dataframe.head(n): Dataframe에서 첫 n개의 행을 출력 (n의 기본값은 5 -> 파라미터 전달x일 시 첫 5개만 출력)
# df.iloc[:n]과 같은 기능
df.head(3)

  city  year  pop
0   서울  2022  0.8
1   서울  2023  0.9
2   서울  2024  9.5

In [142]:
#  Dataframe.head(n): Dataframe에서 끝에서 n개의 행을 출력 (n의 기본값은 5 -> 파라미터 전달x일 시 끝에서 5개만 출력)
# df.iloc[-n:]과 같은 기능
df.tail(2)

  city  year  pop
4   경기  2023  1.2
5   경기  2024  1.1

In [143]:
# Dataframe.column.value_counts(): 각 컬럼의 값들을 counting -> 개수
# df['city'].value_counts()
df.city.value_counts()

city
서울    3
경기    3
Name: count, dtype: int64

In [144]:
df.year.value_counts()

year
2022    2
2023    2
2024    2
Name: count, dtype: int64